# Generated by Django 4.2.4 on 2023-11-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_education_experience_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='profile_picture'),
        ),
    ]
